### ISSUE TITLE
Update to newer Sketch version

### ISSUE THREAD

**Issue by sqrter** [teracyhq/wireframe#11]
Hi,

Thanks for the great wireframe kit. 

Could anyone re-save it with a newer Sketch version. I'm trying to import it in the Gravit Designer, but it requires Teracy_wireframe.sketch to be generated in at least Sketch 43 or latest.

Thanks in advance!

**Comment by renestalder** [comment]
I just opened it with the current Sketch version, saved it and zipped it. Does that the job?

[Teracy_wireframe.sketch.zip](https://github.com/teracyhq/wireframe/files/1580160/Teracy_wireframe.sketch.zip)

**Comment by sqrter** [comment]
@renestalder Oh yes, thank you very much! Now I can use it on my PC 

![gravit-sketch](https://user-images.githubusercontent.com/479984/34277760-d2cc5d7e-e6af-11e7-9a1d-a41717e5c456.png)
