### ISSUE TITLE
Sketch file looks a bit greyed out?

### ISSUE THREAD

**Issue by chufucious** [teracyhq/wireframe#3]
Thanks for this! I just downloaded and opened the file and the contents are looking a bit faded... Is this intentional?

![screenshot 2014-12-10 11 45 15](https://cloud.githubusercontent.com/assets/973029/5379885/16e7878e-8062-11e4-9d9c-ca0871265ddc.png)

**Comment by 0x73706f6f6b** [comment]
@chufucious Just tried it out on a few projects and it looks normal to me, if they're not to your liking perhaps branch off and create a darker version of the sketch file. Then issue a pull-request.

**Comment by chufucious** [comment]
Got it, thanks.

**Comment by sirme87** [comment]
Hi, You can modify the Shared style to customize the Border and Fill to your liking. In your case, try to change the shared style called "Base frame".
